### ISSUE TITLE
有没有windows 版本的

### ISSUE THREAD

**Issue by qincenhua** [DreamedWorker/TravellersBag#4]
我也想使用但是我不是这个系统呀

**Comment by DreamedWorker** [comment]
你好，旅者行囊**尚没有**适配Windows系统的打算，因为已经有「胡桃工具箱」等其他优秀的原神工具箱软件。而且，如果要适配Windows系统和Linux系统，这意味着开发语言和使用的框架**都需要更换**，这会导致软件前后一致性被破坏。
很抱歉，如果说后续却有需求，或者说你有适配能力，非常欢迎你提出pr。
